version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clean_arch_project
    ports:
      - "5432:5432"
